// enemyTypes.js
// EXP MOBS (Mob Lvl - qtdExp)
// Mob1 - 2	Mob2 - 3	Mob3 - 5	Mob4 - 8	Mob5 - 12	Mob6 - 18	Mob7 - 27	Mob8 - 41	Mob9 - 62	Mob10 - 93

export const ENEMY_TYPES = {
  lizard: {
    speed: 140,
    health: 12,
    damage: 1,
    level: 1,
    behavior: "chase",
    detectionRange: 200,
    attackRange: 60,
    attackCooldown: 2000,
    attackTimer: 0,
    color: 0xffffff,
    renderName: "lizard",
    gold: 1,
    exp: 50,
    dropType: "basic",
    renderTexture: {
      walk_se: { start: 0, end: 5, frameRate: 8, repeat: -1 },
      walk_s: { start: 6, end: 11, frameRate: 8, repeat: -1 },
      walk_e: { start: 12, end: 17, frameRate: 8, repeat: -1 },
      walk_ne: { start: 18, end: 23, frameRate: 8, repeat: -1 },
      walk_n: { start: 24, end: 29, frameRate: 8, repeat: -1 },
      idle: { start: 30, end: 38, frameRate: 4, repeat: -1 },
      death: { start: 30, end: 38, frameRate: 4, repeat: 0 },
      atk: { start: 39, end: 47, frameRate: 8, repeat: -1 },
    },
    returnType: {
      canReturnToOrigin: true,
      returnOnPlayerDeath: true,
      leashRange: 300,
    },
    boss: {
      exp: 16,
      gold: 4,
      crystal: 2,
      attackRange: 30,
      health: 120,
      damage: 20,
    },
  },

  bat: {
    speed: 140,
    health: 30,
    damage: 3,
    level: 2,
    behavior: "chase",
    detectionRange: 200,
    attackRange: 60,
    attackCooldown: 2000,
    attackTimer: 0,
    color: 0xffffff,
    renderName: "bat",
    gold: 2,
    exp: 2,
    dropType: "basic",
    renderTexture: {
      atk: { start: 0, end: 3, frameRate: 8, repeat: -1 },
      walk_se: { start: 0, end: 3, frameRate: 8, repeat: -1 },
      walk_s: { start: 0, end: 3, frameRate: 8, repeat: -1 },
      walk_e: { start: 0, end: 3, frameRate: 8, repeat: -1 },
      walk_ne: { start: 0, end: 3, frameRate: 8, repeat: -1 },
      walk_n: { start: 0, end: 3, frameRate: 8, repeat: -1 },
      idle: { start: 8, end: 11, frameRate: 4, repeat: -1 },
      death: { start: 8, end: 11, frameRate: 4, repeat: -1 },
      hit: { start: 4, end: 7, frameRate: 8, repeat: -1 },
    },
    returnType: {
      canReturnToOrigin: true,
      returnOnPlayerDeath: true,
      leashRange: 300,
    },
    boss: {
      exp: 16,
      gold: 4,
      crystal: 2,
      attackRange: 30,
      health: 300,
      damage: 40,
    },
  },

  spider: {
    speed: 140,
    health: 100,
    damage: 9,
    level: 3,
    behavior: "chase",
    detectionRange: 200,
    attackRange: 60,
    attackCooldown: 2000,
    attackTimer: 0,
    color: 0xffffff,
    renderName: "spider",
    gold: 1,
    exp: 1,
    dropType: "basic",
    renderTexture: {
      walk_se: { start: 0, end: 3, frameRate: 8, repeat: -1 },
      walk_s: { start: 4, end: 7, frameRate: 8, repeat: -1 },
      walk_e: { start: 8, end: 11, frameRate: 8, repeat: -1 },
      walk_ne: { start: 12, end: 15, frameRate: 8, repeat: -1 },
      walk_n: { start: 16, end: 19, frameRate: 8, repeat: -1 },
      idle: { start: 20, end: 27, frameRate: 4, repeat: -1 },
      death: { start: 20, end: 27, frameRate: 4, repeat: 0 },
      atk: { start: 28, end: 35, frameRate: 8, repeat: -1 },
    },
    returnType: {
      canReturnToOrigin: true,
      returnOnPlayerDeath: true,
      leashRange: 300,
    },
    boss: {
      exp: 16,
      gold: 4,
      crystal: 2,
      attackRange: 30,
      health: 1000,
      damage: 100,
    },
  },
};
