export const ITEMS_DB = {
  potion_hp_p: {
    id: "potion_hp_p",
    name: "Poção de Vida Pequena",
    rarity: "common",
    type: "consumable",
    price: 25,
    amountable: true,
    use: { type: "heal", value: 50, cooldown: 10000 },
    desc: ["+ 50 Hp Instantâneo", "Cooldown 10s"],
    icon: { texture: "basicItems", frame: 6 },
    loot: { id: "potion_hp_p", rarity: "common", weight: 90, lvl: 1 },
  },
  potion_hp_m: {
    id: "potion_hp_m",
    name: "Poção de Vida Média",
    rarity: "common",
    type: "consumable",
    price: 45,
    amountable: true,
    desc: ["+ 90 Hp Instantâneo", "Cooldown 15s"],
    use: { type: "heal", value: 90, cooldown: 15000 },
    icon: { texture: "basicItems", frame: 8 },
    loot: { id: "potion_hp_m", rarity: "rare", weight: 50, lvl: 1 },
  },
  potion_hp_g: {
    id: "potion_hp_g",
    name: "Poção de Vida Grande",
    type: "consumable",
    rarity: "common",
    amountable: true,
    price: 400,
    desc: ["+ 700 Hp Instantâneo", "Cooldown 30s"],
    use: { type: "heal", value: 700, cooldown: 30000 },
    icon: { texture: "basicItems", frame: 9 },
    loot: { id: "potion_hp_g", rarity: "epic", weight: 10, lvl: 1 },
  },
  laco: {
    id: "laco",
    name: "Laço de Pet",
    type: "consumable",
    rarity: "common",
    amountable: true,
    price: 400,
    use: { type: "event", value: "laco_usado" },
    desc: ["Capture um pet"],
    icon: { texture: "basicItems", frame: 13 },
    loot: { id: "laco", rarity: "common", weight: 2, lvl: 1 },
  },
  sword: {
    name: "Espada Simples",
    type: "equipment",
    rarity: "common",
    amountable: true,
    desc: [],
    slotType: "weapon_left",
    atributes: { damage: 10 },
    icon: { texture: "basicItems", frame: 1 },
    loot: { id: "sword", rarity: "common", weight: 10, lvl: 2 },
  },
  ring: {
    name: "Anel Simples",
    type: "equipment",
    rarity: "common",
    amountable: true,
    desc: [],
    slotType: "ring",
    atributes: { maxHealth: 15 },
    icon: { texture: "basicItems", frame: 3 },
    loot: { id: "ring", rarity: "common", weight: 10, lvl: 1 },
  },
  bota: {
    name: "Bota Simples",
    type: "equipment",
    rarity: "common",
    amountable: true,
    desc: [],
    slotType: "boots",
    atributes: { speed: 10 },
    icon: { texture: "basicItems", frame: 2 },
    loot: { id: "bota", rarity: "common", weight: 10, lvl: 2 },
  },
  shield: {
    name: "Escudo",
    type: "equipment",
    rarity: "common",
    amountable: true,
    desc: [],
    slotType: "weapon_right",
    atributes: { defense: 10 },
    icon: { texture: "basicItems", frame: 0 },
    loot: { id: "shield", rarity: "common", weight: 10, lvl: 2 },
  },
  helmet: {
    name: "capacete",
    type: "equipment",
    rarity: "common",
    amountable: true,
    desc: [],
    slotType: "helmet",
    atributes: { defense: 3 },
    icon: { texture: "basicItems", frame: 11 },
    loot: { id: "helmet", rarity: "common", weight: 10, lvl: 2 },
  },
  armor: {
    name: "Armadura",
    type: "equipment",
    rarity: "common",
    amountable: true,
    desc: [],
    slotType: "armor",
    atributes: { defense: 4 },
    icon: { texture: "basicItems", frame: 12 },
    loot: { id: "armor", rarity: "common", weight: 10, lvl: 2 },
  },
  red_stone: {
    name: "Pedra Vermelha",
    type: "material",
    amountable: true,
    rarity: "epic",
    icon: { texture: "stones", frame: 0 },
    loot: { id: "red_stone", rarity: "epic", weight: 0.1, lvl: 3 },
  },

  blue_stone: {
    name: "Pedra Azul",
    type: "material",
    amountable: true,
    rarity: "common",
    icon: { texture: "stones", frame: 1 },
    loot: { id: "blue_stone", rarity: "common", weight: 2, lvl: 3 },
  },

  green_stone: {
    name: "Pedra Verde",
    type: "material",
    amountable: true,
    rarity: "rare",
    icon: { texture: "stones", frame: 2 },
    loot: { id: "green_stone", rarity: "rare", weight: 0.1, lvl: 3 },
  },

  yellow_stone: {
    name: "Pedra Amarela",
    type: "material",
    amountable: true,
    rarity: "rare",
    icon: { texture: "stones", frame: 3 },
    loot: { id: "yellow_stone", rarity: "rare", weight: 1, lvl: 3 },
  },
  violet_stone: {
    name: "Pedra Violeta",
    type: "material",
    amountable: true,
    rarity: "legendary",
    icon: { texture: "stones", frame: 4 },
    loot: { id: "violet_stone", rarity: "legendary", weight: 0.05, lvl: 3 },
  },
  luck: {
    name: "Item de Sorte",
    type: "material",
    amountable: true,
    rarity: "epic",
    desc: ["Craft de Alto Nível"],
    icon: { texture: "basicItems", frame: 10 },
    loot: { id: "luck", rarity: "epic", weight: 0.05, lvl: 6 },
  },
  pergaminho: {
    name: "Pergaminho",
    type: "material",
    amountable: true,
    rarity: "rare",
    damage: 10,
    icon: { texture: "basicItems", frame: 4 },
    loot: { id: "pergaminho", rarity: "rare", weight: 1, lvl: 4 },
  },
  insignia_power_multi: {
    name: "Insignia de Poder",
    type: "insignia",
    stat: "powerMulti",
    level: 1,
    rarity: "common",
    craftable: true,
    amountable: true,
    bonus: { powerMulti: 5 },
    desc: ["Multiplicador +5%"],
    icon: { texture: "atkicons", frame: 6 },
    loot: {
      id: "insignia_power_multi",
      rarity: "common",
      weight: 1,
      lvl: 5,
    },
  },
  insignia_damage_reduction: {
    name: "Insignia de Defesa",
    type: "insignia",
    stat: "damageReduction",
    level: 1,
    rarity: "common",
    craftable: true,
    amountable: true,
    bonus: { damageReduction: 10 },
    desc: ["Reducao de dano +10%"],
    icon: { texture: "accIcons", frame: 6 },
    loot: {
      id: "insignia_damage_reduction",
      rarity: "common",
      weight: 1,
      lvl: 5,
    },
  },
  insignia_aura_power: {
    name: "Insignia de Aura",
    type: "insignia",
    stat: "auraPower",
    level: 1,
    rarity: "common",
    craftable: true,
    amountable: true,
    bonus: { auraPower: 1 },
    desc: ["Poder de aura +1%"],
    icon: { texture: "accIcons", frame: 6 },
    loot: {
      id: "insignia_aura_power",
      rarity: "common",
      weight: 1,
      lvl: 5,
    },
  },
  insignia_growth: {
    name: "Insignia de Crescimento",
    type: "insignia",
    stat: "growth",
    level: 1,
    rarity: "common",
    craftable: true,
    amountable: true,
    bonus: { growth: 1 },
    desc: ["Crescimento +1%"],
    icon: { texture: "accIcons", frame: 1 },
    loot: {
      id: "insignia_growth",
      rarity: "common",
      weight: 1,
      lvl: 5,
    },
  },
  insignia_amplify: {
    name: "Insignia de Amplificacao",
    type: "insignia",
    stat: "amplify",
    level: 1,
    rarity: "common",
    craftable: true,
    amountable: true,
    bonus: { amplify: 1 },
    desc: ["Amplificacao +1%"],
    icon: { texture: "accIcons", frame: 2 },
    loot: {
      id: "insignia_amplify",
      rarity: "common",
      weight: 1,
      lvl: 5,
    },
  },
  insignia_conversion: {
    name: "Insignia de Conversao",
    type: "insignia",
    stat: "conversion",
    level: 1,
    rarity: "common",
    craftable: true,
    amountable: true,
    bonus: { conversion: 5 },
    desc: ["Conversao +5%"],
    icon: { texture: "accIcons", frame: 3 },
    loot: {
      id: "insignia_conversion",
      rarity: "common",
      weight: 1,
      lvl: 5,
    },
  },
};
